title: "ENSI Showcase Jeux Vidéo"
description: "Vitrine des projets étudiants – École des Nouvelles Images"

url: "https://ecole-des-nouvelles-images.github.io"
baseurl: "/games-showcase"

locale: fr

collections:
  games:
    output: true
    permalink: /games/:name/

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - README.md
